FROM java:8
EXPOSE 9090
ADD /target/user-preferred-amenities-0.0.1-SNAPSHOT.jar user-preferred-amenities-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["/usr/bin/java", "-jar", "user-preferred-amenities-0.0.1-SNAPSHOT.jar"]
